# Generated by Django 5.2.6 on 2025-09-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(db_column='user_id', primary_key=True, serialize=False)),
                ('fname', models.CharField(db_column='fname', max_length=100)),
                ('lname', models.CharField(db_column='lname', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('username', models.CharField(db_column='username', max_length=100, unique=True)),
                ('passwordhash', models.CharField(db_column='passwordhash', max_length=255)),
                ('role', models.CharField(db_column='role', max_length=50)),
            ],
            options={
                'db_table': '"User"',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
