# Generated by Django 5.2.6 on 2025-09-28 02:20

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('descriptor', models.TextField(blank=True, null=True)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=8)),
                ('question_kind', models.CharField(choices=[('mcq', 'Multiple Choice'), ('coding', 'Coding')], max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'questions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coding',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='coding', serialize=False, to='game.question')),
                ('template_code', models.TextField()),
                ('prompt', models.TextField()),
                ('test_cases', models.JSONField()),
                ('time_threshold', models.IntegerField(blank=True, null=True)),
                ('space_threshold', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coding',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['test_cases'], name='idx_coding_cases_gin')],
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mcq', serialize=False, to='game.question')),
                ('choices', models.JSONField()),
                ('answer_index', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'mcq',
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['choices'], name='idx_mcq_choices_gin')],
            },
        ),
    ]
