# Generated by Django 5.2.6 on 2025-09-28 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='begin_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='countdown_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='p1_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(('player1_id', models.F('player2_id')), _negated=True), name='match_not_self'),
        ),
    ]
