# Generated by Django 5.2.6 on 2025-09-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_id', models.IntegerField()),
                ('player2_id', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('finished', 'finished'), ('cancelled', 'cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Widget',
        ),
    ]
