# Generated by Django 5.2.6 on 2025-09-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_kind_first_question_indexes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='first_question',
        ),
        migrations.AddField(
            model_name='match',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='question_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='match',
            name='kind',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('coding', 'Coding')], default='mcq', max_length=6),
        ),
    ]
