# Generated by Django 5.2.6 on 2025-09-28 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_match_first_question_match_p1_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='p1_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='p2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='question_ids',
        ),
        migrations.AddField(
            model_name='match',
            name='first_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_in_matches', to='game.question'),
        ),
    ]
