# Generated by Django 5.2.6 on 2025-09-28 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_remove_match_p1_score_remove_match_p2_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='first_question',
        ),
        migrations.AddField(
            model_name='match',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='question_ids',
            field=models.JSONField(default=list),
        ),
    ]
