# Generated by Django 5.2.6 on 2025-09-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_match_first_question_match_p1_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField()),
                ('question_kind', models.CharField(choices=[('mcq', 'Multiple Choice'), ('coding', 'Coding')], max_length=6)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('is_correct', models.BooleanField()),
                ('elapsed_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'game_results',
                'managed': False,
            },
        ),
    ]
