# Generated by Django 5.2.6 on 2025-09-28 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gameresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.IntegerField(blank=True, null=True)),
                ('event', models.CharField(choices=[('matched', 'Matched'), ('ready', 'Ready toggled'), ('countdown_started', 'Countdown started'), ('activated', 'Match activated'), ('answer', 'Answer submitted'), ('finished', 'Match finished')], max_length=32)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='game.match')),
            ],
            options={
                'db_table': 'match_events',
                'indexes': [models.Index(fields=['match', 'created_at'], name='idx_event_match_time')],
            },
        ),
    ]
